all:
  hosts:
    raspberrypi:
      ansible_host: <YOUR_RASPBERRY_PI_IP>
      ansible_user: <YOUR_SSH_USER>
      ansible_port: 22
      ansible_password: <YOUR_PASSWORD>
      ansible_become: true
      # ansible_ssh_private_key_file: <YOUR_PRIVATE_KEY_FILE>